const persone = [
  {
    nome: "Marco",
    cognome: "Filannino",
    eta: "22",
    livello: 5,
    sesso: "donna",
    email: "filanninobusiness@gmail.com",
    img: "/src/assets/avatar/avatar (3).webp",
    gruppo: "gruppo A",
    monitoraggio: "si",
    password: "ciaociao1!",
    peso: "22",
    attivita: "2",
    sfide: "si",
    sports: {
      running: false,
      escursione: true,
      biking: true,
      camminata: false,
    },
  },
  {
    nome: "Luca",
    cognome: "Rossi",
    eta: "25",
    livello: 2,
    sesso: "uomo",
    email: "lucarossi@gmail.com",
    img: "/src/assets/avatar/avatar (4).webp",
    gruppo: "gruppo B",
    monitoraggio: "no",
    password: "password123",
    peso: "78",
    attivita: "3",
    sfide: "no",
    sports: {
      running: true,
      escursione: false,
      biking: false,
      camminata: true,
    },
  },
  {
    nome: "Anna",
    cognome: "Bianchi",
    eta: "29",
    livello: 42,
    sesso: "donna",
    email: "anna.bianchi@gmail.com",
    img: "/src/assets/avatar/avatar (1).webp",
    gruppo: "gruppo C",
    monitoraggio: "si",
    password: "securepassword!",
    peso: "60",
    attivita: "1",
    sfide: "si",
    sports: { running: true, escursione: true, biking: false, camminata: true },
  },
  {
    nome: "Giulia",
    cognome: "Verdi",
    eta: "27",
    livello: 67,
    sesso: "donna",
    email: "giulia.verdi@gmail.com",
    img: "/src/assets/avatar/avatar (2).webp",
    gruppo: "gruppo D",
    monitoraggio: "no",
    password: "giulia27!",
    peso: "65",
    attivita: "2",
    sfide: "no",
    sports: {
      running: false,
      escursione: false,
      biking: true,
      camminata: false,
    },
  },
  {
    nome: "Simone",
    cognome: "Neri",
    eta: "30",
    livello: 55,
    sesso: "uomo",
    email: "simone.neri@gmail.com",
    img: "/src/assets/avatar/avatar (8).webp",
    gruppo: "gruppo A",
    monitoraggio: "si",
    password: "simone30!",
    peso: "85",
    attivita: "4",
    sfide: "si",
    sports: { running: true, escursione: true, biking: false, camminata: true },
  },
  {
    nome: "Chiara",
    cognome: "Gialli",
    eta: "24",
    livello: 4,
    sesso: "donna",
    email: "chiara.gialli@gmail.com",
    img: "/src/assets/avatar/avatar (5).webp",
    gruppo: "gruppo B",
    monitoraggio: "no",
    password: "chiara24!",
    peso: "55",
    attivita: "3",
    sfide: "no",
    sports: {
      running: false,
      escursione: true,
      biking: true,
      camminata: false,
    },
  },
  {
    nome: "Davide",
    cognome: "Blu",
    eta: "28",
    livello: 9,
    sesso: "uomo",
    email: "davide.blu@gmail.com",
    img: "/src/assets/avatar/avatar (9).webp",
    gruppo: "gruppo C",
    monitoraggio: "si",
    password: "davide28!",
    peso: "80",
    attivita: "5",
    sfide: "si",
    sports: {
      running: false,
      escursione: false,
      biking: false,
      camminata: true,
    },
  },
  {
    nome: "Francesca",
    cognome: "Viola",
    eta: "26",
    livello: 6,
    sesso: "donna",
    email: "francesca.viola@gmail.com",
    img: "/src/assets/avatar/avatar (6).webp",
    gruppo: "gruppo D",
    monitoraggio: "si",
    password: "francesca26!",
    peso: "62",
    attivita: "2",
    sfide: "no",
    sports: { running: true, escursione: true, biking: true, camminata: false },
  },
  {
    nome: "Alessandro",
    cognome: "Bianco",
    eta: "23",
    livello: 28,
    sesso: "uomo",
    email: "alessandro.bianco@gmail.com",
    img: "/src/assets/avatar/avatar (11).webp",
    gruppo: "gruppo A",
    monitoraggio: "no",
    password: "alessandro23!",
    peso: "74",
    attivita: "4",
    sfide: "si",
    sports: {
      running: false,
      escursione: true,
      biking: false,
      camminata: true,
    },
  },
  {
    nome: "Martina",
    cognome: "Rosso",
    eta: "21",
    livello: 45,
    sesso: "donna",
    email: "martina.rosso@gmail.com",
    img: "/src/assets/avatar/avatar (7).webp",
    gruppo: "gruppo B",
    monitoraggio: "si",
    password: "martina21!",
    peso: "58",
    attivita: "3",
    sfide: "si",
    sports: { running: true, escursione: false, biking: true, camminata: true },
  },
];

export default persone;
