const eventiArr = [
  {
    id: 1,
    creatore_evento: 1,
    creatore_nome: "Marco",
    nome_evento: "corsetta mattutina",
    start: "Via della Moscova, Milano",
    finish: "Corso Como, Milano",
    distanza: 12.2,
    orario: "16:00",
    data: "2025-02-24",
    img: "src/assets/placeholder-mappa/map-placeholder.png",
    privacy: "1",
    partecipanti: ["Marco", "Laura", "Sergio"],
  },
  {
    id: 2,
    creatore_evento: 1,
    creatore_nome: "Anna",
    nome_evento: "corsetta pomeridiana",
    start: "Via del Corso, Roma",
    finish: "Via dei Condotti, Roma",
    distanza: 8.1,
    orario: "15:00",
    data: "2025-01-18",
    img: "src/assets/placeholder-mappa/map-placeholder(2).png",
    privacy: "1",
    partecipanti: ["Marcella", "Giovanni"],
  },
  {
    id: 3,
    creatore_evento: 1,
    creatore_nome: "Michele",
    nome_evento: "passeggiata notturna",
    start: "Via Roma, Torino",
    finish: "Via Trinchese, Torino",
    distanza: 4.4,
    orario: "10:00",
    data: "2025-04-05",
    img: "src/assets/placeholder-mappa/map-placeholder(3).png",
    privacy: "1",
    partecipanti: ["Tommaso", "Giuseppe", "Sergio", "Michela"],
  },
];

export default eventiArr;
