const persone = [
  {
    id: 1,
    nome: "Marco",
    cognome: "Filannino",
    eta: "22",
    livello: 5,
    sesso: "donna",
    email: "filanninobusiness@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Helmet-Male.webp",
    gruppo: "gruppo A",
    monitoraggio: "si",
    password: "ciaociao1!",
    peso: "22",
    attivita: "2",
    sfide: "si",
    sports: {
      running: false,
      escursione: true,
      biking: true,
      camminata: false,
    },
  },
  {
    id: 2,
    nome: "Luca",
    cognome: "Rossi",
    eta: "25",
    livello: 2,
    sesso: "uomo",
    email: "lucarossi@gmail.com",
    img: "/src/assets/avatar/Avatar-Yung-Helmet-Male.webp",
    gruppo: "gruppo B",
    monitoraggio: "no",
    password: "password123",
    peso: "78",
    attivita: "3",
    sfide: "no",
    sports: {
      running: true,
      escursione: false,
      biking: false,
      camminata: true,
    },
  },
  {
    id: 3,
    nome: "Anna",
    cognome: "Bianchi",
    eta: "29",
    livello: 42,
    sesso: "donna",
    email: "anna.bianchi@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Helmet-Lady.webp",
    gruppo: "gruppo C",
    monitoraggio: "si",
    password: "securepassword!",
    peso: "60",
    attivita: "1",
    sfide: "si",
    sports: { running: true, escursione: true, biking: false, camminata: true },
  },
  {
    id: 4,
    nome: "Giulia",
    cognome: "Verdi",
    eta: "27",
    livello: 67,
    sesso: "donna",
    email: "giulia.verdi@gmail.com",
    img: "/src/assets/avatar/Avatar-Yung-Helmet-Lady.webp",
    gruppo: "gruppo D",
    monitoraggio: "no",
    password: "giulia27!",
    peso: "65",
    attivita: "2",
    sfide: "no",
    sports: {
      running: false,
      escursione: false,
      biking: true,
      camminata: false,
    },
  },
  {
    id: 5,
    nome: "Simone",
    cognome: "Neri",
    eta: "30",
    livello: 55,
    sesso: "uomo",
    email: "simone.neri@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Hiking-Male.webp",
    gruppo: "gruppo A",
    monitoraggio: "si",
    password: "simone30!",
    peso: "85",
    attivita: "4",
    sfide: "si",
    sports: { running: true, escursione: true, biking: false, camminata: true },
  },
  {
    id: 6,
    nome: "Chiara",
    cognome: "Gialli",
    eta: "24",
    livello: 4,
    sesso: "donna",
    email: "chiara.gialli@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Hiking-Lady.webp",
    gruppo: "gruppo B",
    monitoraggio: "no",
    password: "chiara24!",
    peso: "55",
    attivita: "3",
    sfide: "no",
    sports: {
      running: false,
      escursione: true,
      biking: true,
      camminata: false,
    },
  },
  {
    id: 7,
    nome: "Davide",
    cognome: "Blu",
    eta: "28",
    livello: 9,
    sesso: "uomo",
    email: "davide.blu@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Hiking-Male.webp",
    gruppo: "gruppo C",
    monitoraggio: "si",
    password: "davide28!",
    peso: "80",
    attivita: "5",
    sfide: "si",
    sports: {
      running: false,
      escursione: false,
      biking: false,
      camminata: true,
    },
  },
  {
    id: 8,
    nome: "Francesca",
    cognome: "Viola",
    eta: "26",
    livello: 6,
    sesso: "donna",
    email: "francesca.viola@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Hiking-Lady.webp",
    gruppo: "gruppo D",
    monitoraggio: "si",
    password: "francesca26!",
    peso: "62",
    attivita: "2",
    sfide: "no",
    sports: { running: true, escursione: true, biking: true, camminata: false },
  },
  {
    id: 9,
    nome: "Alessandro",
    cognome: "Bianco",
    eta: "23",
    livello: 28,
    sesso: "uomo",
    email: "alessandro.bianco@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Running-Male.webp",
    gruppo: "gruppo A",
    monitoraggio: "no",
    password: "alessandro23!",
    peso: "74",
    attivita: "4",
    sfide: "si",
    sports: {
      running: false,
      escursione: true,
      biking: false,
      camminata: true,
    },
  },
  {
    id: 10,
    nome: "Martina",
    cognome: "Rosso",
    eta: "21",
    livello: 45,
    sesso: "donna",
    email: "martina.rosso@gmail.com",
    img: "/src/assets/avatar/Avatar-Senior-Running-Lady.webp",
    gruppo: "gruppo B",
    monitoraggio: "si",
    password: "martina21!",
    peso: "58",
    attivita: "3",
    sfide: "si",
    sports: { running: true, escursione: false, biking: true, camminata: true },
  },
];

export default persone;
